(()=>{'use strict';
const KEY='ferias-lucas-monica-config-v5';
const $=id=>document.getElementById(id);const pad=n=>String(n).padStart(2,'0');
const names={0:'Domingo',1:'Segunda',2:'Terça',3:'Quarta',4:'Quinta',5:'Sexta',6:'Sábado'};
const tm=v=>{if(!v)return null;const[a,b]=v.split(':').map(Number);return a*60+b};
const hm=(v,signed=false)=>{let sg=v<0?'−':signed?'+':'';v=Math.abs(Math.round(v));return sg+pad(Math.floor(v/60))+':'+pad(v%60)};
const hms=sec=>{sec=Math.max(0,Math.floor(sec));return String(Math.floor(sec/3600)).padStart(2,'0')+':'+pad(Math.floor(sec%3600/60))+':'+pad(sec%60)};
const dateVal=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){return null}}
function save(c){c.savedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(c))}
function rowMinutes(s){if(!s||!s.active)return 0;let z=0;[[s.a1,s.b1],[s.a2,s.b2]].forEach(([a,b])=>{a=tm(a);b=tm(b);if(a!==null&&b!==null&&b>a)z+=b-a});return z}
function bankMinutes(c){if(!c||!c.bankEnabled)return 0;return Number(c.bankSign||1)*(Math.max(0,Number(c.bankHours)||0)*60+Math.max(0,Math.min(59,Number(c.bankMinutes)||0)))}
function setBank(c,total){total=Math.round(total);c.bankEnabled=true;c.bankSign=total<0?-1:1;total=Math.abs(total);c.bankHours=Math.floor(total/60);c.bankMinutes=total%60}
function dObj(v){if(!v)return null;const[y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)}
function css(){const st=document.createElement('style');st.textContent=`
#bankToolsSection{margin-top:0}.bt-wrap{margin-top:9px;padding:12px;border:1px solid #dce8e9;border-radius:16px;background:#f8fbfb}.bt-off{margin-top:9px}.bt-off label{display:flex;align-items:center;gap:8px;color:#566e72;font-size:11px;font-weight:900}.bt-off input{width:18px;height:18px;accent-color:#004F59}.bt-times{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px;margin-top:10px}.bt-f{min-width:0}.bt-f label{display:block;margin:0 0 5px 2px;color:#596f73;font-size:8px;font-weight:950;text-transform:uppercase}.bt-f input{width:100%;min-width:0;height:43px;border:1px solid #d5e2e3;border-radius:12px;background:#fff;color:#173337;padding:0 6px;font-size:14px}.bt-f input:disabled{opacity:.42;background:#eef3f3}.bt-calc{margin-top:10px;padding:11px;border-radius:13px;background:#eef7f6;color:#557075;font-size:11px;line-height:1.55}.bt-calc strong{color:#173337}.bt-plus{color:#17785c!important}.bt-minus{color:#a34740!important}.bt-remove{width:100%;min-height:42px;margin-top:7px;border:1px solid #dce8e9;border-radius:13px;background:#fff;color:#6a7d81;font-weight:900}.bt-hidden{display:none!important}@media(max-width:430px){.bt-times{grid-template-columns:1fr 1fr}.bt-f input{font-size:16px}}`;
document.head.appendChild(st)}
function inject(){if($('bankToolsSection')||!$('cfgBank'))return;css();$('cfgBank').insertAdjacentHTML('afterend',`<div id="bankToolsSection" class="bt-hidden"><div class="section-title">Jornada diferente / movimentação do banco</div><p class="section-help">Use quando uma data tiver horário diferente do padrão. O app compara a jornada prevista com a informada e calcula quanto entra ou sai do banco.</p><div class="bt-wrap"><div class="field"><label>Data da jornada diferente</label><input type="date" id="btDate"></div><div class="bt-off"><label><input type="checkbox" id="btOff"> Não vou trabalhar neste dia</label></div><div class="bt-times"><div class="bt-f"><label>1ª entrada</label><input type="time" id="btA1"></div><div class="bt-f"><label>1ª saída</label><input type="time" id="btB1"></div><div class="bt-f"><label>2ª entrada</label><input type="time" id="btA2"></div><div class="bt-f"><label>2ª saída</label><input type="time" id="btB2"></div></div><div id="btCalc" class="bt-calc">Escolha uma data para calcular.</div><button id="btApply" type="button" class="secondary">APLICAR JORNADA E VARIAÇÃO</button><button id="btRemove" type="button" class="bt-remove bt-hidden">REMOVER AJUSTE DESTA DATA</button></div></div>`);
$('btDate').value=dateVal(new Date());
$('btDate').addEventListener('change',fill);$('btOff').addEventListener('change',()=>{toggle();calc()});['btA1','btB1','btA2','btB2'].forEach(id=>{$(id).addEventListener('input',calc);$(id).addEventListener('change',calc)});$('btApply').addEventListener('click',apply);$('btRemove').addEventListener('click',remove);
document.querySelectorAll('input[name="cfgHasBank"]').forEach(x=>x.addEventListener('change',refreshVisibility));
$('openSettings')?.addEventListener('click',()=>setTimeout(()=>{refreshVisibility();fill()},0));refreshVisibility();fill()}
function enabledInSettings(){return document.querySelector('input[name="cfgHasBank"]:checked')?.value==='1'}
function refreshVisibility(){if(!$('bankToolsSection'))return;$('bankToolsSection').classList.toggle('bt-hidden',!enabledInSettings())}
function nominalFor(c,v){const d=dObj(v);return d&&c.schedule?rowMinutes(c.schedule[d.getDay()]):0}
function form(){const off=$('btOff').checked;return{active:!off,a1:off?'':$('btA1').value,b1:off?'':$('btB1').value,a2:off?'':$('btA2').value,b2:off?'':$('btB2').value}}
function validate(s){if(!s.active)return'';if(!s.a1||!s.b1)return'Preencha pelo menos a 1ª entrada e a 1ª saída.';const a1=tm(s.a1),b1=tm(s.b1);if(!(a1<b1))return'Revise o primeiro período.';const p2=!!(s.a2||s.b2);if(p2){if(!s.a2||!s.b2)return'Preencha os dois horários do segundo período ou deixe ambos vazios.';const a2=tm(s.a2),b2=tm(s.b2);if(!(b1<=a2&&a2<b2))return'Revise a sequência do segundo período.'}return''}
function fill(){const c=load();if(!c||!$('btDate'))return;const v=$('btDate').value||dateVal(new Date());$('btDate').value=v;c.bankAdjustments=c.bankAdjustments||{};const ex=c.bankAdjustments[v];const d=dObj(v);const base=ex||(c.schedule&&d?c.schedule[d.getDay()]:null)||{active:true,a1:'07:30',b1:'12:00',a2:'13:12',b2:'17:30'};$('btOff').checked=ex?!ex.active:false;$('btA1').value=base.a1||'';$('btB1').value=base.b1||'';$('btA2').value=base.a2||'';$('btB2').value=base.b2||'';$('btRemove').classList.toggle('bt-hidden',!ex);toggle();calc()}
function toggle(){const off=$('btOff').checked;['btA1','btB1','btA2','btB2'].forEach(id=>$(id).disabled=off)}
function calc(){const c=load();if(!c||!$('btDate'))return;const v=$('btDate').value,s=form(),err=validate(s);if(err){$('btCalc').innerHTML=`<strong>${err}</strong>`;return}c.bankAdjustments=c.bankAdjustments||{};const nominal=nominalFor(c,v),actual=rowMinutes(s),delta=actual-nominal,old=c.bankAdjustments[v]?Number(c.bankAdjustments[v].delta)||0:0,projected=bankMinutes(c)-old+delta,cl=delta>0?'bt-plus':delta<0?'bt-minus':'';$('btCalc').innerHTML=`Jornada prevista: <strong>${hm(nominal)}</strong><br>Jornada informada: <strong>${hm(actual)}</strong><br>Variação do banco: <strong class="${cl}">${delta>=0?'+':''}${hm(delta)}</strong><br>Saldo após aplicar: <strong>${hm(projected,true)}</strong>`}
function apply(){const c=load();if(!c)return;const v=$('btDate').value,s=form(),err=validate(s);if(err){$('btCalc').innerHTML=`<strong>${err}</strong>`;return}c.bankAdjustments=c.bankAdjustments||{};const nominal=nominalFor(c,v),actual=rowMinutes(s),delta=actual-nominal,old=c.bankAdjustments[v]?Number(c.bankAdjustments[v].delta)||0:0,newBalance=bankMinutes(c)-old+delta;setBank(c,newBalance);c.bankAdjustments[v]={...s,delta,nominal,actual,savedAt:Date.now()};save(c);$('btCalc').innerHTML=`✓ Ajuste aplicado.<br>Variação: <strong>${delta>=0?'+':''}${hm(delta)}</strong><br>Novo saldo: <strong>${hm(newBalance,true)}</strong>`;setTimeout(()=>location.reload(),700)}
function remove(){const c=load(),v=$('btDate').value;if(!c||!c.bankAdjustments||!c.bankAdjustments[v])return;const old=Number(c.bankAdjustments[v].delta)||0;setBank(c,bankMinutes(c)-old);delete c.bankAdjustments[v];save(c);setTimeout(()=>location.reload(),500)}
function intervals(c,day){const key=dateVal(day),ex=c.bankAdjustments&&c.bankAdjustments[key],s=ex||(c.schedule&&c.schedule[day.getDay()]);if(!s||!s.active)return[];const out=[];[[s.a1,s.b1],[s.a2,s.b2]].forEach(([a,b])=>{if(!a||!b)return;const[ah,am]=a.split(':').map(Number),[bh,bm]=b.split(':').map(Number),st=new Date(day.getFullYear(),day.getMonth(),day.getDate(),ah,am),en=new Date(day.getFullYear(),day.getMonth(),day.getDate(),bh,bm);if(en>st)out.push([st,en])});return out}
function target(c){if(!c.targetDate||!c.targetTime)return null;const[y,m,d]=c.targetDate.split('-').map(Number),[h,mi]=c.targetTime.split(':').map(Number);return new Date(y,m-1,d,h,mi)}
function useful(c,now,t){if(!t||t<=now)return 0;let total=0,cur=new Date(now.getFullYear(),now.getMonth(),now.getDate()),last=new Date(t.getFullYear(),t.getMonth(),t.getDate());for(let i=0;cur<=last&&i<370;i++){for(let[a,b]of intervals(c,cur)){a=a<now?now:a;b=b>t?t:b;if(b>a)total+=b-a}cur.setDate(cur.getDate()+1)}return total/60000}
function state(c,now){for(const[a,b]of intervals(c,now))if(now>=a&&now<b)return`Agora está contando: expediente até ${pad(b.getHours())}:${pad(b.getMinutes())}.`;return'Agora a contagem útil está parada: fora do expediente.'}
function enhanced(){const c=load();if(!c||!$('useful')||$('portalScreen')?.classList.contains('hidden'))return;const now=new Date(),t=target(c),raw=useful(c,now,t),bank=bankMinutes(c),left=Math.max(0,raw*60-bank*60);$('useful').textContent=hms(left);if($('workStatus'))$('workStatus').textContent=left===0&&t&&t>now?'Seu banco cobre todas as horas úteis restantes.':state(c,now);if($('bankNow'))$('bankNow').textContent=c.bankEnabled?hm(bank,true):'Sem banco';if($('targetLine')&&t){const end=t.toLocaleString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});$('targetLine').innerHTML=`Fim do expediente: <strong>${end}</strong><br>Expediente restante: <strong>${hm(raw)}</strong> · Após banco: <strong>${hm(left/60)}</strong>`}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();setInterval(enhanced,300);
})();