(()=>{'use strict';
const CFG='ferias-lucas-monica-config-v8',PREF='ferias-lm-notif-v1';
const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
const prefs=()=>{try{return{enabled:false,last:null,announced:false,snooze:0,...JSON.parse(localStorage.getItem(PREF)||'{}')}}catch(_){return{enabled:false,last:null,announced:false,snooze:0}}};
const save=p=>localStorage.setItem(PREF,JSON.stringify(p));
function target(){try{const c=JSON.parse(localStorage.getItem(CFG)||'null');if(!c?.targetDate||!c?.targetTime)return null;const[y,m,d]=c.targetDate.split('-').map(Number),[h,mi]=c.targetTime.split(':').map(Number);return new Date(y,m-1,d,h,mi).getTime()}catch(_){return null}}
async function notify(title,body,tag){if(Notification.permission!=='granted')return;const r=await navigator.serviceWorker.ready;await r.showNotification(title,{body,icon:'./icon.svg',tag,data:{url:'./index.html'}})}
async function check(){const p=prefs();if(!p.enabled||Notification.permission!=='granted')return;const t=target();if(!t)return;const ms=t-Date.now();if(ms<=0||ms>12*3600000)return;const h=Math.ceil(ms/3600000);if(p.last===h)return;p.last=h;save(p);await notify('🌴 Férias chegando!',`Faltam ${h} ${h===1?'hora':'horas'}!`,`ferias-${h}`)}
function remove(){document.getElementById('notifPrompt')?.remove()}
async function enable(){let x=Notification.permission;if(x==='default')x=await Notification.requestPermission();if(x!=='granted')return;const p=prefs();p.enabled=true;p.announced=true;p.snooze=0;save(p);remove();await notify('🌴 Novidade no contador!','Nas últimas 12 horas antes das férias, você receberá uma contagem regressiva de hora em hora.','ferias-novidade');setTimeout(check,1200)}
function prompt(){if(document.getElementById('notifPrompt'))return;const p=prefs();if(Date.now()<(p.snooze||0))return;const e=document.createElement('div');e.id='notifPrompt';e.innerHTML='<div style="width:min(520px,100%);padding:12px;border:1px solid #dce8e9;border-radius:18px;background:#fffffff8;box-shadow:0 16px 45px #004f5940;color:#173337;font-family:system-ui"><strong style="display:block;font-size:13px">🔔 Contagem regressiva por notificação</strong><span style="display:block;margin-top:4px;color:#687e82;font-size:10px;line-height:1.45">Nas últimas 12 horas, o app avisa a cada hora quantas horas corridas faltam para as férias.</span><div style="display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px"><button id="notifOn" style="min-height:42px;border:0;border-radius:12px;background:#004F59;color:#fff;font-weight:900">ATIVAR</button><button id="notifLater" style="min-height:42px;border:1px solid #dce8e9;border-radius:12px;background:#f3f8f8;color:#61767a;font-weight:900">AGORA NÃO</button></div></div>';Object.assign(e.style,{position:'fixed',zIndex:'90',left:'8px',right:'8px',bottom:'8px',display:'flex',justifyContent:'center'});document.body.appendChild(e);document.getElementById('notifOn').addEventListener('click',enable);document.getElementById('notifLater').addEventListener('click',()=>{const q=prefs();q.snooze=Date.now()+86400000;save(q);remove()})}
async function boot(){if(!standalone()||!('Notification'in window)||!('serviceWorker'in navigator))return;const p=prefs();if(Notification.permission==='granted'&&p.enabled){if(!p.announced){p.announced=true;save(p);await notify('🌴 Novidade no contador!','Nas últimas 12 horas antes das férias, você receberá uma contagem regressiva de hora em hora.','ferias-novidade')}check()}else if(Notification.permission==='default')setTimeout(prompt,800);setInterval(check,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)check()})}
boot();
})();
