(()=>{'use strict';
const CFG='ferias-lucas-monica-config-v8',PREF='ferias-lm-notif-v2';
const VAPID_PUBLIC_KEY='BHR4npmTzBKWQMZPYvoh8wdQIlM6SIvkMSA_f9IeGJNrZH5IHS0PAwCa9saiDJlF1Snn6UMYwlBdXyxFF80KwQ8';
const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
const prefs=()=>{try{return{enabled:false,githubConfigured:false,snooze:0,...JSON.parse(localStorage.getItem(PREF)||'{}')}}catch(_){return{enabled:false,githubConfigured:false,snooze:0}}};
const save=p=>localStorage.setItem(PREF,JSON.stringify(p));
const cfg=()=>{try{return JSON.parse(localStorage.getItem(CFG)||'null')}catch(_){return null}};
function b64ToU8(s){const p='='.repeat((4-s.length%4)%4),b=atob((s+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...b].map(c=>c.charCodeAt(0)))}
async function localNotify(title,body,tag){if(Notification.permission!=='granted')return;const r=await navigator.serviceWorker.ready;await r.showNotification(title,{body,icon:'./icon.svg',badge:'./icon.svg',tag,data:{url:'./index.html'}})}
async function subscription(){const r=await navigator.serviceWorker.ready;let s=await r.pushManager.getSubscription();if(!s)s=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64ToU8(VAPID_PUBLIC_KEY)});return s}
function configJson(s){const c=cfg();if(!c?.targetDate||!c?.targetTime)throw new Error('Defina primeiro a data e o horário final das férias nas configurações.');return JSON.stringify({subscription:s.toJSON(),targetDate:c.targetDate,targetTime:c.targetTime,timezone:'America/Sao_Paulo'})}
function remove(id){document.getElementById(id)?.remove()}
function setupModal(s){remove('pushSetupModal');let value='';try{value=configJson(s)}catch(e){alert(e.message);return}const e=document.createElement('div');e.id='pushSetupModal';e.innerHTML=`<div style="width:min(540px,100%);max-height:92dvh;overflow:auto;padding:15px;border-radius:22px;background:#fff;color:#173337;box-shadow:0 20px 60px #002d3450;font-family:system-ui"><div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start"><div><strong style="display:block;font-size:17px">🔔 Notificações com o app fechado</strong><span style="display:block;margin-top:5px;color:#697e82;font-size:10px;line-height:1.5">Seu celular já criou a inscrição Web Push. Falta salvar esta inscrição como segredo no GitHub.</span></div><button id="pushSetupClose" style="width:38px;height:38px;border:0;border-radius:12px;background:#eef4f4;font-size:20px">×</button></div><div style="margin-top:12px;font-size:10px;font-weight:900;color:#004F59">SECRET: PUSH_CONFIG_JSON</div><textarea id="pushSetupValue" readonly style="width:100%;height:135px;margin-top:6px;padding:9px;border:1px solid #dce8e9;border-radius:12px;background:#f7fafa;color:#314d52;font:10px ui-monospace,monospace;resize:none"></textarea><button id="pushCopy" style="width:100%;min-height:44px;margin-top:8px;border:0;border-radius:12px;background:#004F59;color:#fff;font-weight:900">COPIAR CONFIGURAÇÃO</button><div style="margin-top:10px;padding:10px;border-radius:12px;background:#eef7f6;color:#5c7377;font-size:10px;line-height:1.55">Depois de salvar os dois Secrets no GitHub e executar o teste do workflow, as notificações das últimas 12 horas passam a chegar mesmo sem abrir o aplicativo.</div><button id="pushDone" style="width:100%;min-height:42px;margin-top:8px;border:1px solid #dce8e9;border-radius:12px;background:#f7fafa;color:#61767a;font-weight:900">JÁ CONFIGUREI NO GITHUB</button></div>`;Object.assign(e.style,{position:'fixed',zIndex:'150',inset:'0',display:'grid',placeItems:'end center',padding:'8px',background:'#002d3470'});document.body.appendChild(e);document.getElementById('pushSetupValue').value=value;document.getElementById('pushSetupClose').onclick=()=>remove('pushSetupModal');document.getElementById('pushCopy').onclick=async()=>{try{await navigator.clipboard.writeText(value);document.getElementById('pushCopy').textContent='✓ COPIADO'}catch(_){document.getElementById('pushSetupValue').select()}};document.getElementById('pushDone').onclick=()=>{const p=prefs();p.githubConfigured=true;save(p);remove('pushSetupModal')};e.addEventListener('click',x=>{if(x.target===e)remove('pushSetupModal')})}
function prompt(){if(document.getElementById('notifPrompt'))return;const p=prefs();if(Date.now()<(p.snooze||0))return;const e=document.createElement('div');e.id='notifPrompt';e.innerHTML='<div style="width:min(520px,100%);padding:12px;border:1px solid #dce8e9;border-radius:18px;background:#fffffff8;box-shadow:0 16px 45px #004f5940;color:#173337;font-family:system-ui"><strong style="display:block;font-size:13px">🔔 Ativar notificações das férias</strong><span style="display:block;margin-top:4px;color:#687e82;font-size:10px;line-height:1.45">Ative para receber a contagem regressiva das últimas 12 horas. A etapa final será feita pelo GitHub para funcionar com o app fechado.</span><div style="display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px"><button id="notifOn" style="min-height:42px;border:0;border-radius:12px;background:#004F59;color:#fff;font-weight:900">ATIVAR</button><button id="notifLater" style="min-height:42px;border:1px solid #dce8e9;border-radius:12px;background:#f3f8f8;color:#61767a;font-weight:900">AGORA NÃO</button></div></div>';Object.assign(e.style,{position:'fixed',zIndex:'90',left:'8px',right:'8px',bottom:'8px',display:'flex',justifyContent:'center'});document.body.appendChild(e);document.getElementById('notifOn').onclick=enable;document.getElementById('notifLater').onclick=()=>{const q=prefs();q.snooze=Date.now()+86400000;save(q);remove('notifPrompt')}}
async function enable(){let x=Notification.permission;if(x==='default')x=await Notification.requestPermission();if(x!=='granted')return;try{const s=await subscription();const p=prefs();p.enabled=true;p.githubConfigured=false;p.snooze=0;save(p);remove('notifPrompt');await localNotify('🌴 Contagem regressiva ativada','Agora conclua a configuração no GitHub para receber mesmo com o app fechado.','ferias-push-setup');setupModal(s)}catch(e){alert('Não foi possível criar a inscrição de notificações: '+e.message)}}
async function boot(){if(!standalone()||!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window))return;const p=prefs();if(Notification.permission==='granted'){try{const s=await subscription();p.enabled=true;save(p);if(!p.githubConfigured)setTimeout(()=>setupModal(s),900)}catch(_){}}else if(Notification.permission==='default')setTimeout(prompt,800)}
window.feriasPushSetup=async()=>{if(Notification.permission!=='granted')return enable();const s=await subscription();setupModal(s)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
