(()=>{'use strict';
const START='2026-08-17',END='2026-08-31',CACHE_KEY='ferias-lm-weather-carazinho-v1',CACHE_MS=30*60*1000;
const $=id=>document.getElementById(id);
const pad=n=>String(n).padStart(2,'0');
const fmtDate=s=>{const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d).toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'})};
const codeInfo=c=>{
  if(c===0)return['☀️','Céu limpo'];
  if(c===1)return['🌤️','Predom. limpo'];
  if(c===2)return['⛅','Parcialmente nublado'];
  if(c===3)return['☁️','Nublado'];
  if(c===45||c===48)return['🌫️','Nevoeiro'];
  if([51,53,55,56,57].includes(c))return['🌦️','Garoa'];
  if([61,63,65,66,67].includes(c))return['🌧️','Chuva'];
  if([71,73,75,77,85,86].includes(c))return['🌨️','Neve'];
  if([80,81,82].includes(c))return['🌦️','Pancadas de chuva'];
  if([95,96,99].includes(c))return['⛈️','Trovoadas'];
  return['🌡️','Tempo variável'];
};
function css(){if($('vacWeatherCss'))return;const s=document.createElement('style');s.id='vacWeatherCss';s.textContent=`
#vacWeatherPanel{padding:12px}.vacWeatherBtn{width:100%;min-height:49px;border:0;border-radius:15px;background:linear-gradient(135deg,#0b6d77,#004F59);color:#fff;font:inherit;font-weight:950;box-shadow:0 10px 24px #004f5928}.vacWeatherHint{margin:6px 3px 0;color:#697e82;font-size:9px;text-align:center}.vacWeatherModal{position:fixed;z-index:120;inset:0;display:grid;place-items:end center;padding:8px;background:#002d3470}.vacWeatherBox{width:min(560px,100%);max-height:92dvh;overflow:auto;padding:15px;border-radius:24px;background:#fff;color:#173337;box-shadow:0 20px 60px #002d3450}.vacWeatherHead{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.vacWeatherHead h2{margin:0;font-size:19px}.vacWeatherHead p{margin:4px 0 0;color:#697e82;font-size:10px}.vacWeatherClose{flex:0 0 auto;width:38px;height:38px;border:0;border-radius:12px;background:#eef4f4;color:#004F59;font-size:20px}.vacWeatherMeta{margin:10px 0;padding:9px 10px;border-radius:12px;background:#eef7f6;color:#557075;font-size:10px;line-height:1.45}.vacWeatherList{display:grid;gap:7px}.vacWeatherDay{display:grid;grid-template-columns:72px 1fr auto;gap:8px;align-items:center;padding:10px;border:1px solid #dce8e9;border-radius:14px;background:#f9fbfb}.vacWeatherDate{font-size:10px;font-weight:950;text-transform:capitalize}.vacWeatherCond{display:flex;align-items:center;gap:8px;min-width:0}.vacWeatherIcon{font-size:24px}.vacWeatherDesc{font-size:11px;font-weight:850}.vacWeatherExtra{margin-top:3px;color:#697e82;font-size:9px;line-height:1.4}.vacWeatherTemp{text-align:right;white-space:nowrap}.vacWeatherTemp b{display:block;color:#004F59;font-size:15px}.vacWeatherTemp span{color:#697e82;font-size:9px}.vacWeatherPending{margin-top:9px;padding:10px;border:1px dashed #cbdadb;border-radius:13px;background:#f7fafa;color:#657a7e;font-size:10px;line-height:1.5}.vacWeatherActions{display:grid;grid-template-columns:1fr;gap:7px;margin-top:10px}.vacWeatherRefresh{min-height:43px;border:1px solid #004f5930;border-radius:13px;background:#edf7f6;color:#004F59;font-weight:900}.vacWeatherSource{margin:9px 2px 0;color:#809194;font-size:8px;line-height:1.4;text-align:center}@media(max-width:430px){.vacWeatherDay{grid-template-columns:62px 1fr auto}.vacWeatherDesc{font-size:10px}}
`;document.head.appendChild(s)}
function addUI(){if($('vacWeatherPanel'))return;const content=document.querySelector('#portalScreen .content');if(!content)return;css();const p=document.createElement('section');p.id='vacWeatherPanel';p.className='panel';p.innerHTML=`<button id="vacWeatherOpen" class="vacWeatherBtn">🌦️ PREVISÃO DO TEMPO DAS FÉRIAS</button><div class="vacWeatherHint">Carazinho/RS · 17 a 31 de agosto</div>`;const first=content.querySelector('.panel');first?first.insertAdjacentElement('afterend',p):content.prepend(p);$('vacWeatherOpen').addEventListener('click',openModal)}
function modal(){let m=$('vacWeatherModal');if(m)return m;m=document.createElement('div');m.id='vacWeatherModal';m.className='vacWeatherModal';m.innerHTML=`<div class="vacWeatherBox"><div class="vacWeatherHead"><div><h2>🌦️ Previsão das férias</h2><p>Carazinho, Rio Grande do Sul · 17 a 31 de agosto</p></div><button id="vacWeatherClose" class="vacWeatherClose" aria-label="Fechar">×</button></div><div id="vacWeatherMeta" class="vacWeatherMeta">Carregando previsão atualizada…</div><div id="vacWeatherList" class="vacWeatherList"></div><div id="vacWeatherPending" class="vacWeatherPending" style="display:none"></div><div class="vacWeatherActions"><button id="vacWeatherRefresh" class="vacWeatherRefresh">↻ ATUALIZAR PREVISÃO</button></div><div class="vacWeatherSource">Dados meteorológicos: Open-Meteo. A previsão pode mudar conforme os modelos são atualizados.</div></div>`;document.body.appendChild(m);$('vacWeatherClose').addEventListener('click',()=>m.remove());m.addEventListener('click',e=>{if(e.target===m)m.remove()});$('vacWeatherRefresh').addEventListener('click',()=>load(true));return m}
function cacheRead(){try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'null')}catch(_){return null}}
function cacheWrite(v){try{localStorage.setItem(CACHE_KEY,JSON.stringify(v))}catch(_){}}
async function geocode(){const u='https://geocoding-api.open-meteo.com/v1/search?name=Carazinho&count=5&language=pt&format=json&countryCode=BR';const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('Falha ao localizar Carazinho');const j=await r.json(),a=j.results||[];const x=a.find(v=>String(v.admin1||'').toLowerCase().includes('rio grande do sul'))||a[0];if(!x)throw new Error('Carazinho não encontrado');return{lat:x.latitude,lon:x.longitude,name:x.name,admin1:x.admin1||'Rio Grande do Sul'}}
async function fetchWeather(){const loc=await geocode();const daily='weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum,wind_speed_10m_max';const u=`https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(loc.lat)}&longitude=${encodeURIComponent(loc.lon)}&daily=${daily}&timezone=America%2FSao_Paulo&forecast_days=16`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('Falha ao buscar previsão');const j=await r.json();return{ts:Date.now(),loc,daily:j.daily||{}}}
function rowsFrom(data){const d=data.daily||{},out=[];for(let i=0;i<(d.time||[]).length;i++){const date=d.time[i];if(date<START||date>END)continue;out.push({date,code:d.weather_code?.[i],max:d.temperature_2m_max?.[i],min:d.temperature_2m_min?.[i],rain:d.precipitation_probability_max?.[i],mm:d.precipitation_sum?.[i],wind:d.wind_speed_10m_max?.[i]})}return out}
function pendingAfter(rows){if(!rows.length)return[START,END];const last=rows[rows.length-1].date;if(last>=END)return null;const[y,m,d]=last.split('-').map(Number),n=new Date(y,m-1,d+1),e=new Date(2026,7,31);return[`${n.getFullYear()}-${pad(n.getMonth()+1)}-${pad(n.getDate())}`,`${e.getFullYear()}-${pad(e.getMonth()+1)}-${pad(e.getDate())}`]}
function render(data,stale=false){const rows=rowsFrom(data),list=$('vacWeatherList'),meta=$('vacWeatherMeta'),pending=$('vacWeatherPending');if(!list)return;meta.textContent=`${data.loc?.name||'Carazinho'}/RS · ${stale?'última previsão salva':'atualizada agora'} · janela disponível: até 16 dias`;if(!rows.length){list.innerHTML='<div class="vacWeatherPending">Ainda não há dias do período de férias dentro da janela disponível de previsão.</div>'}else list.innerHTML=rows.map(x=>{const[ic,desc]=codeInfo(Number(x.code));const rain=Number.isFinite(Number(x.rain))?`${Math.round(x.rain)}% de chuva`:'chuva s/ dado';const mm=Number.isFinite(Number(x.mm))?` · ${Number(x.mm).toFixed(1)} mm`:'';const wind=Number.isFinite(Number(x.wind))?` · vento máx. ${Math.round(x.wind)} km/h`:'';return`<div class="vacWeatherDay"><div class="vacWeatherDate">${fmtDate(x.date)}</div><div class="vacWeatherCond"><div class="vacWeatherIcon">${ic}</div><div><div class="vacWeatherDesc">${desc}</div><div class="vacWeatherExtra">${rain}${mm}${wind}</div></div></div><div class="vacWeatherTemp"><b>${Math.round(x.max)}°</b><span>mín. ${Math.round(x.min)}°</span></div></div>`}).join('');const p=pendingAfter(rows);if(p){pending.style.display='block';pending.textContent=`A previsão ainda não alcança ${fmtDate(p[0])}${p[0]!==p[1]?` até ${fmtDate(p[1])}`:''}. Esses dias aparecerão automaticamente conforme entrarem na janela meteorológica disponível.`}else pending.style.display='none'}
async function load(force=false){const m=modal(),old=cacheRead();if(!force&&old&&Date.now()-old.ts<CACHE_MS){render(old,false);return}const meta=$('vacWeatherMeta');if(meta)meta.textContent='Atualizando previsão para Carazinho/RS…';try{const data=await fetchWeather();cacheWrite(data);render(data,false)}catch(e){if(old)render(old,true);else{if(meta)meta.textContent='Não foi possível carregar a previsão agora.';const list=$('vacWeatherList');if(list)list.innerHTML='<div class="vacWeatherPending">Verifique a conexão com a internet e toque em “Atualizar previsão”.</div>'}}}
function openModal(){modal();load(false)}
function boot(){addUI();if(!$('vacWeatherPanel'))setTimeout(addUI,400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
